version: 2

commands:
  configure:
    description: "Configure Git CLI"
    parameters:
      user-email:
        type: string
        default: "compute-ci@computesoftware.com"
      user-name:
        type: string
        default: "compute-ci"

jobs:
  build:
    working_directory: ~/main
    docker:
      - image: circleci/node:12.16.3
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Configure Git
          command:
            git config --global user.email << parameters.user-email >>
            git config --global user.name << parameters.user-name >>
            git branch --set-upstream-to=origin/$CIRCLE_BRANCH $CIRCLE_BRANCH
      - run:
          name: public gh-pages
          command: npm run deploy
  test:
    docker:
      - image: circleci/node:4.8.2-jessie
    steps:
      - checkout
      - run:
          name: Test
          command: npm test
      - run:
          name: Generate code coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
